// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 The semrel Authors
// This code has been partially generated by an AI.

// Package plugin provides a Bitbucket Cloud releases provider that creates
// download entries and annotated tags via the Bitbucket REST API v2.0.
//
// Authentication uses HTTP Basic Auth with an app password:
// https://support.atlassian.com/bitbucket-cloud/docs/app-passwords/
package plugin

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const (
	defaultBaseURL = "https://api.bitbucket.org/2.0"
	defaultTimeout = 30 * time.Second
)

// Client is a Bitbucket Cloud API client for release operations.
type Client struct {
	baseURL          string
	workspace        string
	repoSlug         string
	username         string
	appPassword      string
	http             *http.Client
	commentOnPRs     bool
	commitHashes     []string
	commentConfigErr error
}

// Config configures the Bitbucket client.
type Config struct {
	BaseURL          string
	Workspace        string
	RepoSlug         string
	Username         string
	AppPassword      string
	Timeout          time.Duration
	CommentOnPRs     bool
	CommitHashes     []string
	commentConfigErr error
}

func ConfigFromEnv() Config {
	commentOnPRs, commentConfigErr := parseBool(os.Getenv("SEMREL_PLUGIN_COMMENT_ON_PRS"))
	workspace := strings.TrimSpace(os.Getenv("SEMREL_PLUGIN_WORKSPACE"))
	if workspace == "" {
		workspace = strings.TrimSpace(os.Getenv("BITBUCKET_WORKSPACE"))
	}

	repo := strings.TrimSpace(os.Getenv("SEMREL_PLUGIN_REPO"))
	if repo == "" {
		repo = strings.TrimSpace(os.Getenv("BITBUCKET_REPO_SLUG"))
	}
	if workspace == "" || repo == "" {
		fullName := strings.TrimSpace(os.Getenv("BITBUCKET_REPO_FULL_NAME"))
		parts := strings.SplitN(fullName, "/", 2)
		if len(parts) == 2 {
			if workspace == "" {
				workspace = parts[0]
			}
			if repo == "" {
				repo = parts[1]
			}
		}
	}

	username := strings.TrimSpace(os.Getenv("SEMREL_PLUGIN_USERNAME"))
	if username == "" {
		username = strings.TrimSpace(os.Getenv("BITBUCKET_USERNAME"))
	}

	appPassword := strings.TrimSpace(os.Getenv("SEMREL_PLUGIN_APP_PASSWORD"))
	if appPassword == "" {
		appPassword = strings.TrimSpace(os.Getenv("BITBUCKET_APP_PASSWORD"))
	}

	cfg := Config{
		BaseURL:          coalesce(strings.TrimSpace(os.Getenv("SEMREL_PLUGIN_BASE_URL")), defaultBaseURL),
		Workspace:        workspace,
		RepoSlug:         repo,
		Username:         username,
		AppPassword:      appPassword,
		CommentOnPRs:     commentOnPRs,
		commentConfigErr: commentConfigErr,
	}
	if cfg.CommentOnPRs && cfg.commentConfigErr == nil {
		hashes := strings.TrimSpace(os.Getenv("SEMREL_COMMIT_HASHES"))
		if hashes != "" {
			if err := json.Unmarshal([]byte(hashes), &cfg.CommitHashes); err != nil {
				cfg.commentConfigErr = fmt.Errorf("SEMREL_COMMIT_HASHES must be a JSON array: %w", err)
			}
		}
	}
	return cfg
}

// NewClient creates a new Bitbucket API client.
func NewClient(cfg Config) *Client {
	base := cfg.BaseURL
	if base == "" {
		base = defaultBaseURL
	}
	t := cfg.Timeout
	if t == 0 {
		t = defaultTimeout
	}
	return &Client{
		baseURL:          strings.TrimRight(base, "/"),
		workspace:        cfg.Workspace,
		repoSlug:         cfg.RepoSlug,
		username:         cfg.Username,
		appPassword:      cfg.AppPassword,
		http:             &http.Client{Timeout: t},
		commentOnPRs:     cfg.CommentOnPRs,
		commitHashes:     cfg.CommitHashes,
		commentConfigErr: cfg.commentConfigErr,
	}
}

func New(cfg Config) *Client {
	return NewClient(cfg)
}

// Validate checks provider configuration which can be checked before API calls.
func (cfg Config) Validate() error {
	return cfg.commentConfigErr
}

// CommentOnPullRequests comments once on each pull request associated with a release commit.
func (c *Client) CommentOnPullRequests(ctx context.Context, tagName string) error {
	if c.commentConfigErr != nil {
		return c.commentConfigErr
	}
	if !c.commentOnPRs || len(c.commitHashes) == 0 {
		return nil
	}

	pullRequests := make(map[int64]struct{})
	for _, hash := range c.commitHashes {
		endpoint := fmt.Sprintf("%s/repositories/%s/%s/commit/%s/pullrequests",
			c.baseURL, url.PathEscape(c.workspace), url.PathEscape(c.repoSlug), url.PathEscape(strings.TrimSpace(hash)))
		var response struct {
			Values []struct {
				ID int64 `json:"id"`
			} `json:"values"`
		}
		if err := c.requestJSON(ctx, http.MethodGet, endpoint, nil, &response); err != nil {
			return fmt.Errorf("bitbucket: list pull requests for commit %s: %w", hash, err)
		}
		for _, pr := range response.Values {
			if pr.ID > 0 {
				pullRequests[pr.ID] = struct{}{}
			}
		}
	}

	tagURL := fmt.Sprintf("https://bitbucket.org/%s/%s/commits/tag/%s",
		url.PathEscape(c.workspace), url.PathEscape(c.repoSlug), url.PathEscape(tagName))
	marker := "<!-- semrel-release:" + tagName + " -->"
	message := fmt.Sprintf("%s\nThis pull request has been included in release [%s](%s).", marker, tagName, tagURL)
	for id := range pullRequests {
		commentsURL := fmt.Sprintf("%s/repositories/%s/%s/pullrequests/%d/comments",
			c.baseURL, url.PathEscape(c.workspace), url.PathEscape(c.repoSlug), id)
		var response struct {
			Values []struct {
				Content struct {
					Raw string `json:"raw"`
				} `json:"content"`
			} `json:"values"`
		}
		if err := c.requestJSON(ctx, http.MethodGet, commentsURL+"?pagelen=100", nil, &response); err != nil {
			return fmt.Errorf("bitbucket: list comments for pull request #%d: %w", id, err)
		}
		alreadyCommented := false
		for _, entry := range response.Values {
			if strings.Contains(entry.Content.Raw, marker) {
				alreadyCommented = true
				break
			}
		}
		if alreadyCommented {
			continue
		}
		body, err := json.Marshal(struct {
			Content struct {
				Raw string `json:"raw"`
			} `json:"content"`
		}{Content: struct {
			Raw string `json:"raw"`
		}{Raw: message}})
		if err != nil {
			return fmt.Errorf("bitbucket: marshal release comment for pull request #%d: %w", id, err)
		}
		if err := c.requestJSON(ctx, http.MethodPost, commentsURL, bytes.NewReader(body), nil); err != nil {
			return fmt.Errorf("bitbucket: post release comment to pull request #%d: %w", id, err)
		}
	}
	return nil
}

func (c *Client) requestJSON(ctx context.Context, method, endpoint string, body io.Reader, result any) error {
	req, err := http.NewRequestWithContext(ctx, method, endpoint, body)
	if err != nil {
		return fmt.Errorf("build request: %w", err)
	}
	req.Header.Set("Accept", "application/json")
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	c.setAuth(req)
	resp, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("send request: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode >= http.StatusMultipleChoices {
		return c.apiError("request", resp)
	}
	if result != nil {
		if err := json.NewDecoder(resp.Body).Decode(result); err != nil {
			return fmt.Errorf("decode response: %w", err)
		}
	}
	return nil
}

func parseBool(raw string) (bool, error) {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case "1", "true", "yes", "on":
		return true, nil
	case "":
		return true, nil
	case "0", "false", "no", "off":
		return false, nil
	default:
		return false, fmt.Errorf("SEMREL_PLUGIN_COMMENT_ON_PRS must be a boolean")
	}
}

// Tag represents a Bitbucket repository tag.
type Tag struct {
	Name   string `json:"name"`
	Target struct {
		Hash string `json:"hash"`
	} `json:"target"`
	Message string `json:"message,omitempty"`
}

// CreateTag creates an annotated tag in the Bitbucket repository.
func (c *Client) CreateTag(ctx context.Context, name, commitHash, message string) (*Tag, error) {
	payload := map[string]any{
		"name":    name,
		"target":  map[string]string{"hash": commitHash},
		"message": message,
	}
	body, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("bitbucket: marshal tag payload: %w", err)
	}

	url := fmt.Sprintf("%s/repositories/%s/%s/refs/tags", c.baseURL, c.workspace, c.repoSlug)
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("bitbucket: create tag request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	c.setAuth(req)

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("bitbucket: create tag: %w", err)
	}
	defer func() {
		_ = resp.Body.Close()
	}()

	if resp.StatusCode >= 300 {
		return nil, c.apiError("create tag", resp)
	}

	var responseTag Tag
	if err := json.NewDecoder(resp.Body).Decode(&responseTag); err != nil {
		return nil, fmt.Errorf("bitbucket: decode tag response: %w", err)
	}
	return &responseTag, nil
}

// Download represents a Bitbucket repository download entry.
type Download struct {
	Name  string                       `json:"name"`
	Size  int64                        `json:"size"`
	Links map[string]map[string]string `json:"links,omitempty"`
}

func (c *Client) CreateRelease(ctx context.Context, tagName, changelog string) (*Download, error) {
	fileName := strings.TrimSpace(os.Getenv("SEMREL_PLUGIN_NOTES_FILENAME"))
	if fileName == "" {
		fileName = strings.TrimSpace(tagName) + ".md"
	}
	if strings.TrimSpace(fileName) == "" {
		return nil, fmt.Errorf("bitbucket: tag name is required")
	}
	content := changelog
	if content == "" {
		content = tagName
	}
	return c.uploadDownloadContent(ctx, fileName, []byte(content))
}

// UploadDownload uploads a file to the Bitbucket repository downloads.
func (c *Client) UploadDownload(ctx context.Context, filePath string) (*Download, error) {
	f, err := os.Open(filePath)
	if err != nil {
		return nil, fmt.Errorf("bitbucket: open file: %w", err)
	}
	defer func() { _ = f.Close() }()

	return c.uploadMultipart(ctx, filepath.Base(filePath), f)
}

func (c *Client) uploadDownloadContent(ctx context.Context, name string, content []byte) (*Download, error) {
	return c.uploadMultipart(ctx, name, bytes.NewReader(content))
}

func (c *Client) uploadMultipart(ctx context.Context, name string, content io.Reader) (*Download, error) {
	var buf bytes.Buffer
	mw := multipart.NewWriter(&buf)
	fw, err := mw.CreateFormFile("files", name)
	if err != nil {
		return nil, fmt.Errorf("bitbucket: create form file: %w", err)
	}
	if _, err := io.Copy(fw, content); err != nil {
		return nil, fmt.Errorf("bitbucket: copy file: %w", err)
	}
	if err := mw.Close(); err != nil {
		return nil, fmt.Errorf("bitbucket: close multipart writer: %w", err)
	}

	url := fmt.Sprintf("%s/repositories/%s/%s/downloads", c.baseURL, c.workspace, c.repoSlug)
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, url, &buf)
	if err != nil {
		return nil, fmt.Errorf("bitbucket: upload download request: %w", err)
	}
	req.Header.Set("Content-Type", mw.FormDataContentType())
	c.setAuth(req)

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("bitbucket: upload download: %w", err)
	}
	defer func() {
		_ = resp.Body.Close()
	}()

	if resp.StatusCode >= 300 {
		return nil, c.apiError("upload download", resp)
	}

	return &Download{Name: name}, nil
}

// ListDownloads lists downloads for the repository.
func (c *Client) ListDownloads(ctx context.Context) ([]Download, error) {
	url := fmt.Sprintf("%s/repositories/%s/%s/downloads", c.baseURL, c.workspace, c.repoSlug)
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, fmt.Errorf("bitbucket: list downloads request: %w", err)
	}
	c.setAuth(req)

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("bitbucket: list downloads: %w", err)
	}
	defer func() {
		_ = resp.Body.Close()
	}()

	if resp.StatusCode >= 300 {
		return nil, c.apiError("list downloads", resp)
	}

	var result struct {
		Values []Download `json:"values"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("bitbucket: decode downloads: %w", err)
	}
	return result.Values, nil
}

// PipelineVariable represents a Bitbucket repository variable.
type PipelineVariable struct {
	Key     string `json:"key"`
	Value   string `json:"value"`
	Secured bool   `json:"secured"`
}

// SetPipelineVariable creates or updates a pipeline variable in the repository.
func (c *Client) SetPipelineVariable(ctx context.Context, key, value string, secured bool) error {
	payload := PipelineVariable{Key: key, Value: value, Secured: secured}
	body, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("bitbucket: marshal variable: %w", err)
	}

	url := fmt.Sprintf("%s/repositories/%s/%s/pipelines_config/variables/", c.baseURL, c.workspace, c.repoSlug)
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(body))
	if err != nil {
		return fmt.Errorf("bitbucket: set variable request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	c.setAuth(req)

	resp, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("bitbucket: set variable: %w", err)
	}
	defer func() {
		_ = resp.Body.Close()
	}()

	if resp.StatusCode >= 300 {
		return c.apiError("set pipeline variable", resp)
	}
	return nil
}

func (c *Client) setAuth(req *http.Request) {
	if c.username != "" {
		req.SetBasicAuth(c.username, c.appPassword)
	}
}

func (c *Client) apiError(op string, resp *http.Response) error {
	body, _ := io.ReadAll(io.LimitReader(resp.Body, 512))
	return fmt.Errorf("bitbucket: %s: status %d: %s", op, resp.StatusCode, strings.TrimSpace(string(body)))
}

func coalesce(a, b string) string {
	if a != "" {
		return a
	}
	return b
}
